# Generated by Django 3.2.7 on 2021-10-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_cardsprogramunits'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsfeatures',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardsprogramunits',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detailsubcategory',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
